---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: default
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres
  namespace: default
automountServiceAccountToken: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      service: postgres
      app: postgres
  template:
    metadata:
      labels:
        service: postgres
        app: postgres
      annotations:
        consul.hashicorp.com/connect-inject: "false"
    spec:
      serviceAccountName: postgres
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: NAME
              value: "postgres"
            - name: POSTGRES_HOST_AUTH_METHOD
              value: "trust"
          resources:
            limits:
              cpu: 500m
              memory: 512M
            requests:
              cpu: 500m
              memory: 512M
# run this after RDS is created: 
psql postgresql://postgres:password@learn-consul-7fqh.cvjehh8zzfhg.us-west-2.rds.amazonaws.com:5432/postgres?sslmode=disable
pg_restore .dbexport.pgsql